services:
  server:
    build: ./server
    container_name: server
    ports:
      - "3000:3000"
    environment:
      - CLIENT_ORIGIN=http://localhost
    restart: unless-stopped
  client:
    build:
      context: ./client
      args:
        VITE_BE_URL: http://localhost:3000
    container_name: client
    ports:
      - "80:8080"
    depends_on:
      - server
    restart: unless-stopped
